# Data Cleansing

In [4]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv('survey_results_public.csv', index_col = 0)

In [6]:
df.head()

Professional  \
Respondent                                                      
1                                                     Student   
2                                                     Student   
3                                      Professional developer   
4           Professional non-developer who sometimes write...   
5                                      Professional developer   

                         ProgramHobby         Country      University  \
Respondent                                                              
1                           Yes, both   United States              No   
2                           Yes, both  United Kingdom  Yes, full-time   
3                           Yes, both  United Kingdom              No   
4                           Yes, both   United States              No   
5           Yes, I program as a hobby     Switzerland              No   

                                  EmploymentStatus  \
Respondent                                           
1           Not employed, and not looking for work   
2                               Employed part-time   
3                               Employed full-time   
4                               Employed full-time   
5                               Employed full-time   

                                              FormalEducation  \
Respondent                                                      
1                                            Secondary school   
2           Some college/university study without earning ...   
3                                           Bachelor's degree   
4                                             Doctoral degree   
5                                             Master's degree   

                                           MajorUndergrad  \
Respondent                                                  
1                                                     NaN   
2                Computer science or software engineering   
3                Computer science or software engineering   
4           A non-computer-focused engineering discipline   
5                Computer science or software engineering   

                                                   HomeRemote  \
Respondent                                                      
1                                                         NaN   
2                       More than half, but not all, the time   
3           Less than half the time, but at least one day ...   
4           Less than half the time, but at least one day ...   
5                                                       Never   

                         CompanySize  \
Respondent                             
1                                NaN   
2                 20 to 99 employees   
3           10,000 or more employees   
4           10,000 or more employees   
5                 10 to 19 employees   

                                                  CompanyType      ...        \
Respondent                                                         ...         
1                                                         NaN      ...         
2           Privately-held limited company, not in startup...      ...         
3                                 Publicly-traded corporation      ...         
4           Non-profit/non-governmental organization or pr...      ...         
5           Privately-held limited company, not in startup...      ...         

           StackOverflowMakeMoney Gender HighestEducationParents  \
Respondent                                                         
1               Strongly disagree   Male             High school   
2               Strongly disagree   Male       A master's degree   
3                        Disagree   Male   A professional degree   
4                        Disagree   Male       A doctoral degree   
5                             NaN    NaN                     NaN   

                                    Race   

The objectives of this data cleansing are: <br>
- Convert all five-points measures into numeric data (1-5)
- Convert all yes or no data into 1 and 0
- For the multiple choices columns, I separate those choices into list for further use
- For the columns has string instead of float, for example, yearsprogram, I set them into the mean of the years

### Convert 5 points values

In [59]:
df.replace({'Strongly agree': 5, 'Agree': 4, 
            'Somewhat agree': 3, 'Disagree': 2, 'Strongly disagree': 1}, inplace = True)

In [60]:
df.replace({'Very important': 5, 
            'Important': 4, 'Somewhat important': 3, 
            'Not very important': 2, 'Not at all important': 1}, inplace = True)

In [61]:
df.replace({'Greatly overpaid': 5, 'Somewhat overpaid': 4, 'Neither underpaid nor overpaid': 3, 
            'Somewhat underpaid': 2, 'Greatly underpaid':1},inplace=True)

In [62]:
df.replace({'Very satisfied':5,'Somewhat satisfied':3,
             'satisfied':4,'Not very satisfied':2,
             'Not at all satisfied':1}, inplace = True)

### YearsProgram

In [7]:
df.YearsProgram.unique()

array(['2 to 3 years', '9 to 10 years', '20 or more years',
       '14 to 15 years', '6 to 7 years', '10 to 11 years',
       '13 to 14 years', '12 to 13 years', '15 to 16 years',
       '11 to 12 years', '8 to 9 years', '5 to 6 years', '18 to 19 years',
       '7 to 8 years', '1 to 2 years', '3 to 4 years', 'Less than a year',
       '4 to 5 years', '17 to 18 years', '16 to 17 years',
       '19 to 20 years', nan], dtype=object)

In [8]:
df['YearsProgram'].replace({
    '2 to 3 years': 2.5, '9 to 10 years': 9.5,
    '20 or more years': 20, '14 to 15 years': 14.5,
    '6 to 7 years': 6.5, '10 to 11 years':10.5, '13 to 14 years':13.5, 
    '12 to 13 years': 12.5, '15 to 16 years':15.5, '11 to 12 years': 11.5,
    '8 to 9 years': 8.5, '5 to 6 years' : 5.5, '18 to 19 years' : 18.5,
    '7 to 8 years' : 7.5, '1 to 2 years' : 1.5, '3 to 4 years' : 3.5, 'Less than a year' : 0.5,
    '4 to 5 years' : 4.5, '17 to 18 years' : 17.5, '16 to 17 years' : 16.5,
    '19 to 20 years' : 19.5 }, inplace = True)

<div class="alert alert-block alert-info">
20 or more years : 20  <br>
less than a year : 0.5 

In [9]:
df.YearsProgram.head(5)

Respondent
1     2.5
2     9.5
3    20.0
4    14.5
5    20.0
Name: YearsProgram, dtype: float64

### YearsCodedJob

In [11]:
df.YearsCodedJob.unique()

array([nan, '20 or more years', '9 to 10 years', '10 to 11 years',
       '8 to 9 years', '7 to 8 years', '11 to 12 years', '15 to 16 years',
       '1 to 2 years', '3 to 4 years', '12 to 13 years',
       'Less than a year', '5 to 6 years', '16 to 17 years',
       '13 to 14 years', '6 to 7 years', '2 to 3 years', '17 to 18 years',
       '4 to 5 years', '14 to 15 years', '18 to 19 years',
       '19 to 20 years'], dtype=object)

In [12]:
df['YearsCodedJob'].replace({
    '2 to 3 years': 2.5, '9 to 10 years': 9.5,
    '20 or more years': 20, '14 to 15 years': 14.5,
    '6 to 7 years': 6.5, '10 to 11 years':10.5, '13 to 14 years':13.5, 
    '12 to 13 years': 12.5, '15 to 16 years':15.5, '11 to 12 years': 11.5,
    '8 to 9 years': 8.5, '5 to 6 years' : 5.5, '18 to 19 years' : 18.5,
    '7 to 8 years' : 7.5, '1 to 2 years' : 1.5, '3 to 4 years' : 3.5, 'Less than a year' : 0.5,
    '4 to 5 years' : 4.5, '17 to 18 years' : 17.5, '16 to 17 years' : 16.5,
    '19 to 20 years' : 19.5 }, inplace = True)

In [13]:
df.YearsCodedJob.head()

Respondent
1     NaN
2     NaN
3    20.0
4     9.5
5    10.5
Name: YearsCodedJob, dtype: float64

### YearsCodedJobPast

In [15]:
df.YearsCodedJobPast.unique()

array([nan, '17 to 18 years', '5 to 6 years', '19 to 20 years',
       '7 to 8 years', '4 to 5 years', '14 to 15 years',
       '20 or more years', '2 to 3 years', 'Less than a year',
       '10 to 11 years', '6 to 7 years', '9 to 10 years',
       '11 to 12 years', '3 to 4 years', '13 to 14 years',
       '15 to 16 years', '1 to 2 years', '8 to 9 years', '16 to 17 years',
       '12 to 13 years', '18 to 19 years'], dtype=object)

In [16]:
df['YearsCodedJobPast'].replace({
    '2 to 3 years': 2.5, '9 to 10 years': 9.5,
    '20 or more years': 20, '14 to 15 years': 14.5,
    '6 to 7 years': 6.5, '10 to 11 years':10.5, '13 to 14 years':13.5, 
    '12 to 13 years': 12.5, '15 to 16 years':15.5, '11 to 12 years': 11.5,
    '8 to 9 years': 8.5, '5 to 6 years' : 5.5, '18 to 19 years' : 18.5,
    '7 to 8 years' : 7.5, '1 to 2 years' : 1.5, '3 to 4 years' : 3.5, 'Less than a year' : 0.5,
    '4 to 5 years' : 4.5, '17 to 18 years' : 17.5, '16 to 17 years' : 16.5,
    '19 to 20 years' : 19.5 }, inplace = True)

In [17]:
df.YearsCodedJobPast.head(10)

Respondent
1    NaN
2    NaN
3    NaN
4    NaN
5    NaN
6    NaN
7    NaN
8    NaN
9    NaN
10   NaN
Name: YearsCodedJobPast, dtype: float64

<div class="alert alert-block alert-info">
We have more than 50000 nan for this columns!

### Developer Type

In [28]:
DT = df.DeveloperType[df['DeveloperType'].notnull().tolist()]

In [23]:
DTlist = []
for i in DT:
    t = i.replace(" ","").replace("[","").replace(";"," ").split()
    DTlist.append(t)

In [24]:
DTs = str(DTlist)
replace = ["[", "]", "'", "'"," "]
for i in replace:
    if i in DTs:
        DTs = DTs.replace(i,'')

In [25]:
DTl = DTs.split(",")

In [26]:
DTU = []
for w in DTl:
    if w not in DTU:
        DTU.append(w)

print(DTU)

['Other', 'Mobiledeveloper', 'Graphicsprogramming', 'Desktopapplicationsdeveloper', 'Webdeveloper', 'Embeddedapplications/devicesdeveloper', 'DevOpsspecialist', 'Qualityassuranceengineer', 'Datascientist', 'Machinelearningspecialist', 'Developerwithastatisticsormathematicsbackground', 'Databaseadministrator', 'Systemsadministrator', 'Graphicdesigner']


Unique Developer Type we have: <br>
'Other', 'Mobiledeveloper', 'Graphicsprogramming', 'Desktopapplicationsdeveloper', 'Webdeveloper', 'Embeddedapplications/devicesdeveloper', 'DevOpsspecialist', 'Qualityassuranceengineer', 'Datascientist', 'Machinelearningspecialist', 'Developerwithastatisticsormathematicsbackground', 'Databaseadministrator', 'Systemsadministrator', 'Graphicdesigner'

##### Distinguished by Developer

<div class="alert alert-block alert-info">
- Developer: 'Mobiledeveloper', 'Desktopapplicationsdeveloper', 'Embeddedapplications/devicesdeveloper','Developerwithastatisticsormathematicsbackground'  <br>
- Non-developer:'Graphicsprogramming','DevOpsspecialist','Qualityassuranceengineer','Datascientist','Machinelearningspecialist','Databaseadministrator', 'Systemsadministrator', 'Graphicdesigner'

In [29]:
df['IsDeveloper'] = df.DeveloperType[df['DeveloperType'].notnull()].apply(
    lambda x: 1 if 'developer' in x else 0)

##### Distinguished by Data Scientist

In [30]:
NDT = df.NonDeveloperType[df['NonDeveloperType'].notnull().tolist()]

In [31]:
NDTlist = []
for i in NDT:
    t = i.replace(" ","").replace("[","").replace(";"," ").split()
    NDTlist.append(t)

In [32]:
NDTs = str(NDTlist)

In [33]:
replace = ["[", "]", "'", "'"," "]
for i in replace:
    if i in NDTs:
        NDTs = NDTs.replace(i,'')

In [34]:
NDTl = NDTs.split(",")

In [35]:
NDTU = []
for w in NDTl:
    if w not in NDTU:
        NDTU.append(w)

print(NDTU)

['Datascientist', 'Other', 'C-suiteexecutive', 'Productmanager', 'Educatororacademic', 'Analystorconsultant', 'Marketingorsalesmanager', 'Designerorillustrator', 'Electedofficial']


<div class="alert alert-block alert-info">
- Data: 'Datascientist', 'Machinelearningspecialist', 'Developerwithastatisticsormathematicsbackground', 'Databaseadministrator', 'Analystorconsultant'<br>
- Non-Data: 'Other', 'Mobiledeveloper', 'Graphicsprogramming', 'Desktopapplicationsdeveloper', 'Webdeveloper', 'Embeddedapplications/devicesdeveloper', 'DevOpsspecialist', 'Qualityassuranceengineer','Systemsadministrator', 'Graphicdesigner','C-suiteexecutive', 'Productmanager', 'Educatororacademic', 'Marketingorsalesmanager', 'Designerorillustrator', 'Electedofficial'

### Career Satisfaction

In [36]:
df.CareerSatisfaction.unique()

array([nan,  8.,  6.,  7.,  3.,  9.,  5., 10.,  4.,  0.,  2.,  1.])

In [37]:
df['CareerSatisfactionDummy'] = df.CareerSatisfaction[
    df['CareerSatisfaction'].notnull()].apply(lambda x: 1 if x >= 7 else 0)

In [38]:
df.CareerSatisfactionDummy.unique()

array([nan,  1.,  0.])

In [39]:
df.astype(str).groupby('CareerSatisfactionDummy')['Professional'].count()

CareerSatisfactionDummy
0.0    11287
1.0    31408
nan     8697
Name: Professional, dtype: int64

### Job Satisfaction

In [40]:
df.JobSatisfaction.unique()

array([nan,  9.,  3.,  8.,  6.,  7.,  5.,  4., 10.,  2.,  0.,  1.])

In [41]:
df['JobSatisfactionDummy'] = df.JobSatisfaction[
    df['JobSatisfaction'].notnull()].apply(lambda x: 1 if x >= 7 else 0)

In [42]:
df.JobSatisfactionDummy.unique()

array([nan,  1.,  0.])

In [43]:
df.astype(str).groupby('JobSatisfactionDummy')['Professional'].count()

JobSatisfactionDummy
0.0    13703
1.0    26673
nan    11016
Name: Professional, dtype: int64

### Job Seeking Status

In [44]:
df.JobSeekingStatus.unique()

array(["I'm not actively looking, but I am open to new opportunities",
       nan, 'I am actively looking for a job',
       'I am not interested in new job opportunities'], dtype=object)

In [45]:
df['JobSeekingStatusDummy'] = df.JobSeekingStatus[
    df['JobSeekingStatus'].notnull()].apply(lambda x: 1 if x.startswith("I am actively") else 0)

In [47]:
df[['JobSeekingStatusDummy','JobSeekingStatus']].head(10)

JobSeekingStatusDummy  \
Respondent                          
1                             0.0   
2                             NaN   
3                             NaN   
4                             1.0   
5                             NaN   
6                             0.0   
7                             0.0   
8                             0.0   
9                             0.0   
10                            0.0   

                                             JobSeekingStatus  
Respondent                                                     
1           I'm not actively looking, but I am open to new...  
2                                                         NaN  
3                                                         NaN  
4                             I am actively looking for a job  
5                                                         NaN  
6           I'm not actively looking, but I am open to new...  
7           I'm not actively looking, but I am open to new...  
8           I'm not actively looking, but I am open to new...  
9                I am not interested in new job opportunities  
10          I'm not actively looking, but I am open to new...

In [48]:
df.astype(str).groupby('JobSeekingStatusDummy')['Professional'].count()

JobSeekingStatusDummy
0.0    29009
1.0     4371
nan    18012
Name: Professional, dtype: int64

### Last New Job

<div class="alert alert-block alert-info">
0:less than 2 <br>
1:greater than 2

In [49]:
df.LastNewJob.unique()

array(['Not applicable/ never', nan, 'Between 2 and 4 years ago',
       'More than 4 years ago', 'Less than a year ago',
       'Between 1 and 2 years ago'], dtype=object)

In [50]:
df['LastNewJobDummy'] = df['LastNewJob'].replace({
    'Not applicable/ never': 0, 'Between 2 and 4 years ago': 1,
    'More than 4 years ago': 1, 'Less than a year ago': 0,
    'Between 1 and 2 years ago': 0})

In [51]:
df.astype(str).groupby('LastNewJobDummy')['Professional'].count()

LastNewJobDummy
0.0    20572
1.0    12138
nan    18682
Name: Professional, dtype: int64

### Job Profile

In [52]:
df.JobProfile.unique()

array(['Other', nan, 'LinkedIn; Other', 'LinkedIn',
       'LinkedIn; Monster; Other', 'LinkedIn; Xing',
       'Indeed; LinkedIn; Monster', 'LinkedIn; Monster',
       'Indeed; LinkedIn', 'LinkedIn; Naukri', 'Xing',
       'JobSite.co.uk; LinkedIn',
       'Dice; Glassdoor; Hired.com; Indeed; LinkedIn; Monster',
       'LinkedIn; Reed.co.uk', 'Hired.com; LinkedIn; Other',
       'LinkedIn; Remix_jobs',
       'Dice; Glassdoor; Hired.com; Indeed; LinkedIn; Monster; TripleByte',
       'Indeed; StepStone', 'Dice', 'Indeed; LinkedIn; Monster; Naukri',
       'LinkedIn; Monster; Naukri', 'Glassdoor; Indeed; LinkedIn',
       'Indeed; LinkedIn; TripleByte', 'Glassdoor; LinkedIn; Monster',
       'Dice; Glassdoor; Hired.com; LinkedIn; Monster', 'Monster',
       'Hired.com; LinkedIn; Monster; Other', 'CW_Jobs; Indeed',
       'Dice; Indeed; Monster', 'LinkedIn; Other; Xing',
       'Dice; Indeed; LinkedIn; Monster', 'CW_Jobs; LinkedIn',
       'LinkedIn; Monster; Workopolis',
       'Glassd

In [53]:
JP = df.JobProfile[df['JobProfile'].notnull().tolist()]

In [54]:
JPlist = []
for i in JP:
    t = i.replace(" ","").replace("[","").replace(";"," ").split()
    JPlist.append(t)

In [55]:
JPs = str(JPlist)

In [56]:
replace = ["[", "]", "'", "'"," "]
for i in replace:
    if i in JPs:
        JPs = JPs.replace(i,'')

In [57]:
JPl = JPs.split(",")

In [58]:
JPU = []
for w in JPl:
    if w not in JPU:
        JPU.append(w)

print(JPU)

['Other', 'LinkedIn', 'Monster', 'Xing', 'Indeed', 'Naukri', 'JobSite.co.uk', 'Dice', 'Glassdoor', 'Hired.com', 'Reed.co.uk', 'Remix_jobs', 'TripleByte', 'StepStone', 'CW_Jobs', 'Workopolis', 'Total_Jobs', 'Pracuj', 'Talent.io']
